name: Deploy Release
on:
  release:
    types: [published]

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
  deploy:
    needs: run-tests
    uses: ./.github/workflows/deploy.yaml
    with:
      aws-env: "development"
      github-env: "production"
