name: Deploy PR to a Staging Environment
on:
  issue_comment:
    types: [created]

jobs:
  check-pr-comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github.event) }}'
