name: Deploy PR to a Staging Environment
on:
  issue_comment:
    types: [created]

jobs:
  check-pr-comment:
    if: ${{ github.event.issue.pull_request && github.event.issue.state == 'open' && github.event.comment.body == '/deploy' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github.event) }}'
      - name: Get Pull Request and Check Status
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            const response = github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.issue.number
            });
            console.log(response.data)
