name: Deploy PR to a Staging Environment
on:
  issue_comment:
    types: [created]

jobs:
  get-pr-head:
    if: ${{ github.event.issue.pull_request && github.event.issue.state == 'open' && github.event.comment.body == '/deploy' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      pr-ref: ${{ steps.get-head-ref.outputs.result }}
    steps:
      - run: echo '${{ toJson(github.event) }}'
      - name: Get Pull Request Head Ref
        id: get-head-ref
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
            });
            return response.data.head.ref
      - name: Update Pull Request
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const comment = `⏳ Deployment should start in a moment...

            [You can monitor the progress here.](https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            })

  deploy-pr:
    needs: get-pr-head
    secrets: inherit
    uses: ./.github/workflows/deploy.yaml
    with:
      aws-env: "my-app-pr-${{ github.event.issue.number }}"
      github-env: "staging"
      ref: ${{ needs.get-pr-head.outputs.pr-ref }}
